development:
  adapter: mysql2
  database: baltbear
  host: localhost
  username: root
  password: 
  
production:
  adapter: mysql2
  database: cfb
  host: localhost
  username: cfb_app
  password: Bwg74p2*
  encoding: utf8

migrate:
  adapter: mysql2
  database: cfb
  host: localhost
  username: cfb_migrate
  password: e#3O17lw
